baseURL = 'https://agile.vc/'
languageCode = 'en'
title = 'Agile Partners - Venture Capital for Software Founders'
theme = 'archie'

[params]
  mode = "toggle"
  useCDN = true
  subtitle = ""
  description = "Founders backing founders. Early-stage VC in Berlin & Europe. Often the first backers of technical teams."
  og_image = "/og-image.png"
  customCSS = ["css/custom.css"]
  customJS = ["/js/custom.js"]
